# Generated by Django 4.1 on 2022-08-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_id",
        ),
    ]
