# Generated by Django 4.1 on 2022-10-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_issue_issue_comment_project_project_members_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment_id",
        ),
    ]
