# Generated by Django 4.1 on 2022-10-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0005_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
